### ISSUE TITLE
setTrustedHeaderName deprecated

### ISSUE THREAD

**Issue by timersys** [fideloper/TrustedProxy#83]
The "Symfony\Component\HttpFoundation\Request::setTrustedHeaderName()" method is deprecated since version 3.3 and will be removed in 4.0. Use the $trustedHeaderSet argument of the Request::setTrustedProxies() method instead.

\Fideloper\Proxy\TrustProxies::setTrustedProxyHeaderNames

**Comment by torrancemiller** [comment]
Experiencing this same issue in Laravel 5.5 application.

**Comment by fideloper** [comment]
By "issue", I'm guessing you get a deprecation notice in PHP if that error reporting level has that set to show up?

**Comment by neeravp** [comment]
@fideloper In Laravel 5.5.21, I am getting an error rather than just a warning. Please let me know a temp workaround if you still intend to keep it backwards compatible. Thanks.

**Comment by fideloper** [comment]
For Laravel 5.5, did y'all run `composer require...` and then follow the docs here?

If you did, that's actually a mistake since Laravel 5.5 includes this package out of the box and has it's own configuration for it. I've updated the readme to show that.

Here are the docs for using this package with Laravel 5.5: https://laravel.com/docs/5.5/requests#configuring-trusted-proxies (note you wont need to do any composer things, it's there with laravel out of the box).


If you did it that way (with the included implementation) and still have errors, let me know!

**Comment by bradmang18** [comment]
So, I've been all over the place trying to make sense of this issue.  I understand that using the instructions you provided in the URL above advises how to set up trusted proxies and headers from a configuration standpoint.  But it still doesn't address the issue of your package calling a deprecated function.  The second the handle function is called in the \Fideloper\Proxy\TrustProxies class, the deprecated function will be called, regardless of what I'm configuring in the Laravel TrustProxies class.

Could you please tell me what I should be doing differently that would prevent the function from being called and/or what I am misunderstanding?

Thanks!!!

**Comment by fideloper** [comment]
Laravel 5.5 out of the box doesn't have this error right? That's the real question I guess. Do you have time to test that out?

I forget if Laravel changes PHP's `error_reporting` setting to perhaps show depreciated warnings in your code that might not appear in everyone else's, but that's another angle of attack as well.

**Comment by bradmang18** [comment]
Laravel 5.5 does have this error out of the box.  Laravel does not change your php.ini error_reporting setting as far as I can tell.  For the time being I have updated my error_reporting to E_ALL & ~E_USER_DEPRECATED to suppress this error.

Are you opposed to me creating a PR to remove usage of the deprecated functions?  I'd be happy to contribute.  My thought is you could tag a new version after my PR and users can opt to update their composer.json dependency to use the new version should they so choose.
